### ISSUE TITLE
Issue validating against `!include`d JSON schemas in `types`

### ISSUE THREAD

**Issue by jstoiko** [mulesoft-labs/osprey-method-handler#29]
E.g.
```
#%RAML 1.0
title: My api
baseUri: http://localhost:3000

types:
  Foo: !include schemas/foo.json

/foo:
  post:
    body:
      application/json:
        type: Foo
```

Either replacing `foo.json` by an equivalent RAML datatype `foo.raml` or replacing `type: Foo` by `schema: !include schemas/foo.json` works.

--
originally submitted here: https://github.com/mulesoft/osprey/issues/151
